name: seangine
version: 0.2.0.0
synopsis: A Vulkan renderer by and for Sean Gillespie
description: A Vulkan renderer by and for Sean Gillespie
homepage: https://github.com/sgillespie/seangine
license: MIT
license-file: LICENSE
author: Sean D Gillespie
maintainer: sean@mistersg.net
copyright: "2021"
category: Graphics

data-files:
  - data/cube.gltf

dependencies:
  - base
  - extra
  - gltf-loader
  - resourcet
  - rio
  - vector
  - vulkan

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumDecimals
  - OverloadedLists
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

language: Haskell2010
  
library:
  other-modules:
    - Graphics.Seangine.Instance.PhysicalDeviceDetails
    - Graphics.Seangine.Frame.BufferDetails
    - Graphics.Seangine.Frame.DescriptorSets
    - Graphics.Seangine.Frame.GraphicsPipelineDetails
    - Graphics.Seangine.Frame.SwapchainDetails
    - Graphics.Seangine.Internal.Utils
  dependencies:
    - bytestring
    - linear
    - microlens
    - transformers
    - unliftio-core
    - sdl2
    - text
    - vulkan-utils
    - VulkanMemoryAllocator
  source-dirs: lib

executables:
  seangine:
    main: Main.hs
    dependencies:
      - filepath
      - seangine
    source-dirs: app

tests:
  seangine-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec
    build-tools: hspec-discover:hspec-discover
